### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by AnjaH8** [wanglabcumc/CAMEOS#1]
Hello,

I downloaded CAMEOS and installed everything mentioned in the manual. I tried it both on windows and on a linux virtual machine. However, when I run the example I get the following error:

julia> cd("CAMEOS-master/main")
julia> main.jl example.txt
ERROR: syntax: extra token "example" after end of expression

I hope you can help me solve this problem.
Thanks,
Anja

**Comment by tomblaze** [comment]
Based on the `julia >` in your issue, it looks like you're running this in the julia REPL (what you get after typing `julia`).

In the manual the lines beginning with `$` indicate a standard (i.e. bash) shell, so don't enter `julia`, just run the command from the shell as:

`julia main.jl example.txt`

**Comment by AnjaH8** [comment]
Thank you very much! That helped a lot.
I also added the output directory and changed the example file ("output/" to "output"). It is working better now. Unfortunately, it stops at the step "Evaluating HMM seeds". I get the error that ".jld" is an unknown format (see attachments) although I installed the JLD package and the hdf5-tools.

I hope you can help me again.
Thanks,
Anja

[log_ZokjSNVO.txt](https://github.com/wanglabcumc/CAMEOS/files/3766862/log_ZokjSNVO.txt)
[problem_runs_0.txt](https://github.com/wanglabcumc/CAMEOS/files/3766863/problem_runs_0.txt)

**Comment by tomblaze** [comment]
Odd error. I suspect that the issue is the jld files are truncated, possibly because our account is above the quota for downloaded files.

I increased the quota, could you try downloading the jld files again from https://github.com/wanglabcumc/CAMEOS/tree/master/main/jlds and replacing your current local versions? 

aroB.jld should be 444 MB and infA.jld should be 18 MB.

Running md5sum on the downloaded files should give:

af0a9df70c0d408476ae1c17b3261852  aroB.jld 
8b8eaf1f0459df87e088d6da887712d5  infA.jld 

Hopefully this solves the issue.

**Comment by AnjaH8** [comment]
It is working! 
Thank you so much for your help!
Cheers,
Anja
